[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "azure.openai.responses"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["AI", "Azure", "Azure OpenAI", "Responses", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.openai.responses"

[build-options]
observabilityIncluded = true
