// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
public type ConnectionConfig record {|
    # Provides Auth configurations needed when communicating with a remote HTTP endpoint.
    http:BearerTokenConfig|ApiKeysConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional,
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Provides API key configurations needed when communicating with a remote HTTP endpoint.
public type ApiKeysConfig record {|
    string api\-key;
    string authorization;
|};

# The explicit Azure AI Foundry Models API version to use for this request.
public type AzureAIFoundryModelsApiVersion "v1"|"preview";

# Query parameters for creating a response.
public type CreateResponseQueries record {
    # The explicit Azure AI Foundry Models API version to use for this request.
    # `v1` if not otherwise specified.
    AzureAIFoundryModelsApiVersion api\-version?;
};

# The model response object returned by the Responses API.
public type inline_response_200_5 record {
    # Set of 16 key-value pairs that can be attached to an object.
    OpenAI\.Metadata metadata?;
    int? top_logprobs?;
    decimal? temperature = 1;
    decimal? top_p = 1;
    # This field is being replaced by `safety_identifier` and `prompt_cache_key`.
    #
    # # Deprecated
    @deprecated
    string user?;
    # A stable identifier used to help detect users of your application that may be violating OpenAI's usage policies.
    string safety_identifier?;
    # Used by OpenAI to cache responses for similar requests to optimize your cache hit rates.
    string prompt_cache_key?;
    "in-memory"|"24h"? prompt_cache_retention?;
    string? previous_response_id?;
    # Model ID used to generate the response, like `gpt-4o` or `o3`.
    string model?;
    # Configuration options for reasoning models.
    OpenAI\.Reasoning reasoning?;
    boolean? background?;
    int? max_output_tokens?;
    int? max_tool_calls?;
    # Configuration options for a text response from the model.
    OpenAI\.ResponseTextParam text?;
    # An array of tools the model may call while generating a response.
    OpenAI\.ToolsArray tools?;
    # Reference to a prompt template and its variables.
    OpenAI\.Prompt prompt?;
    "auto"|"disabled"? truncation = "disabled";
    # Unique identifier for this Response.
    string id;
    # The object type of this resource - always set to `response`.
    "response" 'object;
    # The status of the response generation.
    "completed"|"failed"|"in_progress"|"cancelled"|"queued"|"incomplete" status?;
    # Unix timestamp (in seconds) of when this Response was created.
    int created_at;
    int? completed_at?;
    # An error object returned when the model fails to generate a Response.
    OpenAI\.ResponseError 'error?;
    OpenAI\.ResponseIncompleteDetails incomplete_details?;
    # An array of content items generated by the model.
    OpenAI\.OutputItem[] output;
    string|OpenAI\.InputItem[]? instructions;
    string? output_text?;
    # Represents token usage details including input tokens, output tokens,
    # a breakdown of output tokens, and the total tokens used.
    OpenAI\.ResponseUsage usage?;
    # Whether to allow the model to run tool calls in parallel.
    boolean parallel_tool_calls = true;
    # The conversation that this response belonged to.
    OpenAI\.ConversationReference conversation?;
    # The content filter results from RAI.
    AzureContentFilterForResponsesAPI[] content_filters?;
};

# Request body for creating a model response.
public type OpenAI\.CreateResponse record {
    OpenAI\.Metadata metadata?;
    int? top_logprobs?;
    decimal? temperature = 1;
    decimal? top_p = 1;
    string user?;
    string safety_identifier?;
    string prompt_cache_key?;
    "in-memory"|"24h"? prompt_cache_retention?;
    string? previous_response_id?;
    string model?;
    OpenAI\.Reasoning reasoning?;
    boolean? background?;
    int? max_output_tokens?;
    int? max_tool_calls?;
    OpenAI\.ResponseTextParam text?;
    OpenAI\.ToolsArray tools?;
    OpenAI\.ToolChoiceParam tool_choice?;
    OpenAI\.Prompt prompt?;
    "auto"|"disabled"? truncation = "disabled";
    OpenAI\.InputParam input?;
    OpenAI\.IncludeEnum[]? include?;
    boolean? parallel_tool_calls = true;
    boolean? store = true;
    string? instructions?;
    boolean? 'stream?;
    OpenAI\.ResponseStreamOptions stream_options?;
    OpenAI\.ConversationParam conversation?;
};

# An empty metadata record.
public type OpenAI\.Metadata record {
};

# Configuration options for reasoning models.
public type OpenAI\.Reasoning record {
    OpenAI\.ReasoningEffort? effort?;
    "auto"|"concise"|"detailed"? summary?;
    "auto"|"concise"|"detailed"? generate_summary?;
};

# Input parameter for a response - either a string or array of input items.
public type OpenAI\.InputParam string|OpenAI\.InputItem[];

# Fields to include in the response.
public type OpenAI\.IncludeEnum string|"file_search_call.results"|"web_search_call.results"|"web_search_call.action.sources"|"message.input_image.image_url"|"computer_call_output.output.image_url"|"code_interpreter_call.outputs"|"reasoning.encrypted_content"|"message.output_text.logprobs";

# An error object returned when the model fails to generate a Response.
public type OpenAI\.ResponseError record {
    OpenAI\.ResponseErrorCode code;
    string message;
};

# Options for streaming responses.
public type OpenAI\.ResponseStreamOptions record {
    boolean include_obfuscation?;
};

# Variables for a reusable prompt template.
public type OpenAI\.ResponsePromptVariables record {
};

# An input item (message or item reference).
public type OpenAI\.InputItem record {
    OpenAI\.InputItemType 'type;
};

# An array of tools the model may call.
public type OpenAI\.ToolsArray OpenAI\.Tool[];

# Conversation parameter - either a conversation ID string or a conversation object.
public type OpenAI\.ConversationParam string|OpenAI\.ConversationParam\-2;

# Configuration options for a text response from the model.
public type OpenAI\.ResponseTextParam record {
    OpenAI\.TextResponseFormatConfiguration format?;
    OpenAI\.Verbosity? verbosity?;
};

# Reference to a reusable prompt template.
public type OpenAI\.Prompt record {
    string id;
    string? version?;
    OpenAI\.ResponsePromptVariables variables?;
};

# A reference to an existing conversation.
public type OpenAI\.ConversationReference record {
    string id;
};

# Token usage details for a response.
public type OpenAI\.ResponseUsage record {
    int input_tokens;
    OpenAI\.ResponseUsageInputTokensDetails input_tokens_details;
    int output_tokens;
    OpenAI\.ResponseUsageOutputTokensDetails output_tokens_details;
    int total_tokens;
};

# An output item generated by the model.
public type OpenAI\.OutputItem record {
    OpenAI\.OutputItemType 'type;
};

# How the model should select which tool to use.
public type OpenAI\.ToolChoiceParam record {
    OpenAI\.ToolChoiceParamType 'type;
};

# A conversation object with an ID.
public type OpenAI\.ConversationParam\-2 record {
    string id;
};

# Details about why a response was incomplete.
public type OpenAI\.ResponseIncompleteDetails record {
    "max_output_tokens"|"content_filter" reason?;
};

# A tool the model may call.
public type OpenAI\.Tool record {
    OpenAI\.ToolType 'type;
};

# Breakdown of output token usage.
public type OpenAI\.ResponseUsageOutputTokensDetails record {
    int reasoning_tokens;
};

# Breakdown of input token usage.
public type OpenAI\.ResponseUsageInputTokensDetails record {
    int cached_tokens;
};

# Format configuration for text responses.
public type OpenAI\.TextResponseFormatConfiguration record {
    OpenAI\.TextResponseFormatConfigurationType 'type;
};

# The reasoning effort level.
public type OpenAI\.ReasoningEffort "none"|"minimal"|"low"|"medium"|"high"|"xhigh"?;

# Error codes for response generation failures.
public type OpenAI\.ResponseErrorCode "server_error"|"rate_limit_exceeded"|"invalid_prompt"|"vector_store_timeout"|"invalid_image"|"invalid_image_format"|"invalid_base64_image"|"invalid_image_url"|"image_too_large"|"image_too_small"|"image_parse_error"|"image_content_policy_violation"|"invalid_image_mode"|"image_file_too_large"|"unsupported_image_media_type"|"empty_image_file"|"failed_to_download_image"|"image_file_not_found";

# Type of output item.
public type OpenAI\.OutputItemType string|"output_message"|"file_search_call"|"function_call"|"web_search_call"|"computer_call"|"reasoning"|"compaction"|"image_generation_call"|"code_interpreter_call"|"local_shell_call"|"shell_call"|"shell_call_output"|"apply_patch_call"|"apply_patch_call_output"|"mcp_call"|"mcp_list_tools"|"mcp_approval_request"|"custom_tool_call";

# Type of input item.
public type OpenAI\.InputItemType string|"message"|"item_reference";

# Type of tool.
public type OpenAI\.ToolType string|"function"|"file_search"|"computer_use_preview"|"web_search"|"mcp"|"code_interpreter"|"image_generation"|"local_shell"|"shell"|"custom"|"web_search_preview"|"apply_patch";

# Type of text response format.
public type OpenAI\.TextResponseFormatConfigurationType string|"text"|"json_schema"|"json_object";

# Type of tool choice parameter.
public type OpenAI\.ToolChoiceParamType string|"allowed_tools"|"function"|"mcp"|"custom"|"apply_patch"|"shell"|"file_search"|"web_search_preview"|"computer_use_preview"|"web_search_preview_2025_03_11"|"image_generation"|"code_interpreter";

# Verbosity level for responses.
public type OpenAI\.Verbosity "low"|"medium"|"high"?;

# Offsets for a content filter result.
public type AzureContentFilterResultOffsets record {
    int:Signed32 start_offset;
    int:Signed32 end_offset;
    int:Signed32 check_offset;
};

# Content filter results for an Azure Responses API response item.
public type AzureContentFilterForResponsesAPI record {
    # Indicate if the response is blocked.
    boolean blocked;
    # The name of the source type of the message.
    string source_type;
    # A content filter result for a single response item produced by a generative AI system.
    AzureContentFilterResultsForResponsesAPI content_filter_results;
    AzureContentFilterResultOffsets content_filter_offsets;
};

# Detailed content filter results for a Responses API item.
public type AzureContentFilterResultsForResponsesAPI record {
    AzureContentFilterSeverityResult sexual?;
    AzureContentFilterSeverityResult hate?;
    AzureContentFilterSeverityResult violence?;
    AzureContentFilterSeverityResult self_harm?;
    AzureContentFilterDetectionResult profanity?;
    AzureContentFilterBlocklistResult custom_blocklists?;
    AzureContentFilterCustomTopicResult custom_topics?;
    AzureContentFilterResultForChoice_error 'error?;
    # A detection result that describes user prompt injection attacks, where malicious users deliberately exploit system vulnerabilities to elicit unauthorized behavior from the LLM.
    AzureContentFilterDetectionResult jailbreak?;
    # A detection result that indicates if the execution flow still sticks the plan.
    AzureContentFilterDetectionResult task_adherence?;
    AzureContentFilterDetectionResult protected_material_text?;
    AzureContentFilterResultForChoice_protected_material_code protected_material_code?;
    AzureContentFilterCompletionTextSpanDetectionResult ungrounded_material?;
    AzureContentFilterPersonallyIdentifiableInformationResult personally_identifiable_information?;
    AzureContentFilterDetectionResult indirect_attack?;
};

# A severity-based content filter result.
public type AzureContentFilterSeverityResult record {
    boolean filtered;
    "safe"|"low"|"medium"|"high" severity;
};

# A binary detection content filter result.
public type AzureContentFilterDetectionResult record {
    boolean filtered;
    boolean detected;
};

# A blocklist content filter result.
public type AzureContentFilterBlocklistResult record {
    boolean filtered;
    AzureContentFilterBlocklistResult_details[] details?;
};

# Details for a single blocklist entry result.
public type AzureContentFilterBlocklistResult_details record {
    boolean filtered;
    string id;
};

# A custom topic content filter result.
public type AzureContentFilterCustomTopicResult record {
    boolean filtered;
    AzureContentFilterCustomTopicResult_details[] details?;
};

# Details for a single custom topic result.
public type AzureContentFilterCustomTopicResult_details record {
    boolean detected;
    string id;
};

# Content filter result for protected material code.
public type AzureContentFilterResultForChoice_protected_material_code record {
    boolean filtered;
    boolean detected;
    AzureContentFilterResultForChoice_protected_material_code_citation citation?;
};

# Citation details for protected material code.
public type AzureContentFilterResultForChoice_protected_material_code_citation record {
    string license?;
    string URL?;
};

# A span detection result for completion text.
public type AzureContentFilterCompletionTextSpanDetectionResult record {
    boolean filtered;
    boolean detected;
    AzureContentFilterCompletionTextSpan[] details;
};

# A span within completion text.
public type AzureContentFilterCompletionTextSpan record {
    int:Signed32 completion_start_offset;
    int:Signed32 completion_end_offset;
};

# An error in content filtering.
public type AzureContentFilterResultForChoice_error record {
    int:Signed32 code;
    string message;
};

# Personally identifiable information detection result.
public type AzureContentFilterPersonallyIdentifiableInformationResult AzureContentFilterDetectionResult;
